name: Webhook build landing
on:
  repository_dispatch:
    types:
      - build-landing
env:
  LANDING_NAME: ${{ github.event.client_payload.landing_name }}
jobs:
  build-landing:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "Landing name ${{ env.LANDING_NAME }}"
