name: Create landing
on:
  workflow_dispatch:
    inputs:
      landing_name:
        description: "New landing-name"
        required: true
        type: string
      landing_tech:
        required: true
        type: choice
        description: "HBS or Astro"
        options:
          - hbs
          - astro
        default: hbs
  repository_dispatch:
    types:
      - create-landing
env:
  LANDING_NAME: ${{ github.event.inputs.landing_name || github.event.client_payload.landing_name }}
  LANDING_CMS: ${{ github.event.inputs.landing_tech || github.event.client_payload.landing_tech }}
jobs:
  clone-landing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Echo test
        run: echo "${{ env.LANDING_NAME }} ${{ env.LANDING_CMS }}"

      - name: Call script
        run: |
          npm run test -- ${{ env.LANDING_NAME }} ${{ env.LANDING_CMS }}
