name: Clone landing
on:
  workflow_dispatch:
    inputs:
      landing_name:
        description: "New landing_name"
        required: true
        type: string
  repository_dispatch:
    types:
      - create-landing
env:
  LANDING_NAME: ${{github.event.inputs.landing_name || github.event.client_payload.landing_name }}
jobs:
  clone-landing:
    steps:
      - name: Echo test
        run: echo "Landing name ${{ env.LANDING_NAME }}"
